run:
  tests: false
  output:
    format: tab
  modules-download-mode: vendor
linters:
  enable:
    - unconvert
    - megacheck
    - structcheck
    - gas
    - gocyclo
    - dupl
    - misspell
    - unparam
    - varcheck
    - deadcode
    - typecheck
    - ineffassign
    - varcheck
  disable-all: false
