name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker version
      run: docker version
    - name: Build image
      run: |
        docker build \
        --build-arg COVERALLS_TOKEN=$COVERALLS_TOKEN \
        .
      env:
        COVERALLS_TOKEN: ${{secrets.COVERALLS_TOKEN}}